### PR TITLE
Improve latest issue display

### PR DESCRIPTION
**Pull request by ngsilverman**
I thought it might be nice to highlight the latest issue on the homepage and link directly to the content. I took a shot but I'm open to feedback.

## Current

Screenshot 2024-07-03 at 5 32 58 PM

## My Proposal

Screenshot 2024-07-03 at 5 29 19 PM

### CODE REVIEW

**Comment by ngsilverman** [comment]
Changed the headers to be lowercase because _ni li nasin pi toki pona_:

Screenshot 2024-07-04 at 2 11 02 PM

**Comment by alifeee** [comment]
I like this a lot ! thanks for trying something out :-)

image

What do you think of a title-centred version? I attempted the centre as I felt like the section above the list of `toki` was strangely empty. But I'm no designer ;]

image

Looks great on small screen sizes, too :)

image

I am ready to merge this as-is, or I will leave it up to you if you'd like to make some more style changes.

thanks!!!

**Review by alifeee — APPROVED** [review]

**Comment by ngsilverman** [comment]
@alifeee I hear you on the empty space above the list of `toki`. However I would like to progressively move away from things being centered on the page, especially text, because I think it makes it harder to read since there's no consistent left edge. My suggestion would be to rework the section above which I'm happy to do in the near future. ☺️

**Comment by ngsilverman** [comment]
@alifeee looks like you'll need to approve this again 😅

Here's what it looks like with the latest change for the new issue:

Screenshot 2024-07-05 at 4 33 05 PM

**Review by alifeee — APPROVED** [review]
yes! wonderful :)

**Comment by alifeee** [comment]
some small suggestions



the image could be centred in its container

the labels could disallow wrapping inside themselves (i.e., the symbol for musi and the word musi should stay together) 

neither that important, just noticed at a glance. Looks good!

**Pull request merged**
